import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";
import { Metadata } from "next";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Katiem",
  description: "Generated by Katiem",
};

import { NotificationProvider } from "@/context/NotificationContext";

export default function CommonLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <NotificationProvider>
      <div>
        <Navbar />
        {children}
        <Toaster />
        <Footer />
      </div>
    </NotificationProvider>
  );
}
