import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";
import { Metadata } from "next";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Katiem",
  description: "Generated by Katiem",
};


import { myFetch } from "@/utils/myFetch";

export default async function CommonLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  const response = await myFetch("/user/profile", {
    method: "GET",
    tags: ["user"],
  });
  // console.log("Layout User Data:", response);

  return (
    <div>
      <Navbar userData={response?.data} />
      {children}
      <Toaster />
      <Footer />
    </div>
  );
}
