
import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";
import { Metadata } from "next";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Katiem",
  description: "Generated by Katiem",
};


export default function CommonLayout({children}: Readonly<{children: React.ReactNode}>) {
  
  return (
    <div>
      <Navbar />
      {children}
      <Toaster />
      <Footer />
    </div>
  );
}
